name: Continuous Integration, Delivery and Deployment with Github Actions and .NET 10

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create SQL Server Container
      run: |
        docker run -d --name sqlserver_test \
        -e "ACCEPT_EULA=Y" \
        -e "MSSQL_SA_PASSWORD=@Admin1234"
        -p 1433:1433 \
        mcr.microsoft.com/mssql/server:2022-latest

        timeout 90s bash -c "until docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P '@Admin1234' -Q 'SELECT 1' -C; do sleep 5; done"

    - name: Create SQL Server Database
      run: docker exec sqlserver_test /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P '@Admin1234' -Q "IF DB_ID('asp_net_10_erudio') IS NULL CREATE DATABASE [asp_net_10_erudio]" -C

    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    
    - name: Restore .NET Application Dependencies
      run: dotnet restore SolutionErudioLecture.slnx
    
    - name: Build .NET Application Code
      run: dotnet build SolutionErudioLecture.slnx --configuration Release --no-restore
    
    - name: Run Application Tests
      run: dotnet test SolutionErudioLecture.slnx --configuration Release --no-build --logger "console;verbosity=detailed"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
